"""Initial migration

Revision ID: 34b9d3c6a45f
Revises: 
Create Date: 2026-02-12 01:42:47.310744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b9d3c6a45f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('fiscal_year_start', sa.Integer(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fact_daily_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('revenue_gross', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_net', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refunds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('disputes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_ads_meta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_ads_google', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_transaction_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_fixed_allocated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_variable', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transactions_count', sa.Integer(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='idx_financials_user_date_unique')
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    op.drop_table('fact_daily_financials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
